// Dataset de emojis con su nombre en español, agrupados por categoría.
// Lo que va entre paréntesis sirve como palabras clave extra para el buscador.

export const CATEGORIES = [
  { id: 'caras', name: 'Caras y emociones', icon: '😀' },
  { id: 'personas', name: 'Personas y gestos', icon: '👋' },
  { id: 'naturaleza', name: 'Animales y naturaleza', icon: '🐶' },
  { id: 'comida', name: 'Comida y bebida', icon: '🍕' },
  { id: 'actividades', name: 'Actividades', icon: '⚽' },
  { id: 'viajes', name: 'Viajes y lugares', icon: '🚀' },
  { id: 'objetos', name: 'Objetos', icon: '💡' },
  { id: 'simbolos', name: 'Símbolos', icon: '❤️' }
]

const DATA = {
  caras: [
    ['😀', 'cara sonriente'],
    ['😃', 'cara sonriente con ojos grandes'],
    ['😄', 'cara sonriente con ojos alegres'],
    ['😁', 'cara radiante'],
    ['😆', 'cara riendo con ojos cerrados'],
    ['😅', 'cara sonriente con sudor'],
    ['🤣', 'revolcándose de risa'],
    ['😂', 'llorando de risa'],
    ['🙂', 'cara ligeramente sonriente'],
    ['😉', 'cara guiñando un ojo'],
    ['😊', 'cara feliz sonrojada'],
    ['😇', 'cara con aureola (ángel)'],
    ['🥰', 'cara sonriente con corazones (amor)'],
    ['😍', 'cara con ojos de corazón (enamorado)'],
    ['🤩', 'cara con estrellas (alucinando)'],
    ['😘', 'cara lanzando un beso'],
    ['😋', 'cara saboreando comida (rico)'],
    ['😜', 'cara guiñando y sacando la lengua'],
    ['🤔', 'cara pensativa (pensando)'],
    ['🤫', 'cara pidiendo silencio'],
    ['😐', 'cara neutral'],
    ['🙄', 'cara con ojos en blanco'],
    ['😴', 'cara durmiendo (sueño)'],
    ['😎', 'cara con gafas de sol (guay)'],
    ['🤓', 'cara de empollón (gafas)'],
    ['😢', 'cara llorando (triste)'],
    ['😭', 'cara llorando a mares'],
    ['😡', 'cara enfadada (enfado)'],
    ['🤯', 'cabeza explotando'],
    ['🥳', 'cara de fiesta (celebración)'],
    ['🤖', 'robot'],
    ['💩', 'caca'],
    ['👻', 'fantasma']
  ],
  personas: [
    ['👋', 'mano saludando (hola, adiós)'],
    ['✋', 'mano levantada'],
    ['👌', 'señal de ok'],
    ['🤌', 'dedos juntos (italiano)'],
    ['✌️', 'victoria (paz)'],
    ['🤞', 'dedos cruzados (suerte)'],
    ['🤟', 'te quiero con la mano'],
    ['🤘', 'cuernos (rock)'],
    ['👈', 'dedo apuntando a la izquierda'],
    ['👉', 'dedo apuntando a la derecha'],
    ['👆', 'dedo apuntando arriba'],
    ['👇', 'dedo apuntando abajo'],
    ['👍', 'pulgar arriba (me gusta)'],
    ['👎', 'pulgar abajo (no me gusta)'],
    ['✊', 'puño en alto'],
    ['👊', 'puñetazo'],
    ['👏', 'aplausos'],
    ['🙌', 'manos celebrando'],
    ['🙏', 'manos juntas (por favor, gracias)'],
    ['💪', 'bíceps (fuerza)'],
    ['🧠', 'cerebro'],
    ['👀', 'ojos (mirando)'],
    ['🧑‍💻', 'persona programando (ordenador)'],
    ['🦸', 'superhéroe'],
    ['🧙', 'mago'],
    ['🥷', 'ninja'],
    ['💃', 'mujer bailando'],
    ['🕺', 'hombre bailando'],
    ['🏃', 'persona corriendo']
  ],
  naturaleza: [
    ['🐶', 'perro'],
    ['🐱', 'gato'],
    ['🐭', 'ratón'],
    ['🐹', 'hámster'],
    ['🐰', 'conejo'],
    ['🦊', 'zorro'],
    ['🐻', 'oso'],
    ['🐼', 'panda'],
    ['🐨', 'koala'],
    ['🐯', 'tigre'],
    ['🦁', 'león'],
    ['🐮', 'vaca'],
    ['🐷', 'cerdo'],
    ['🐸', 'rana'],
    ['🐵', 'mono'],
    ['🐔', 'gallina'],
    ['🐧', 'pingüino'],
    ['🦄', 'unicornio'],
    ['🐝', 'abeja'],
    ['🦋', 'mariposa'],
    ['🐢', 'tortuga'],
    ['🐙', 'pulpo'],
    ['🐬', 'delfín'],
    ['🐳', 'ballena'],
    ['🦖', 'dinosaurio (t-rex)'],
    ['🌵', 'cactus'],
    ['🌻', 'girasol (flor)'],
    ['🌸', 'flor de cerezo'],
    ['🌳', 'árbol'],
    ['🍀', 'trébol de cuatro hojas (suerte)'],
    ['🍁', 'hoja de arce (otoño)'],
    ['🌈', 'arcoíris'],
    ['☀️', 'sol'],
    ['🌙', 'luna'],
    ['❄️', 'copo de nieve (frío)']
  ],
  comida: [
    ['🍎', 'manzana'],
    ['🍊', 'mandarina (naranja)'],
    ['🍋', 'limón'],
    ['🍌', 'plátano'],
    ['🍉', 'sandía'],
    ['🍇', 'uvas'],
    ['🍓', 'fresa'],
    ['🍒', 'cerezas'],
    ['🍑', 'melocotón'],
    ['🍍', 'piña'],
    ['🥑', 'aguacate'],
    ['🍅', 'tomate'],
    ['🌽', 'maíz'],
    ['🥕', 'zanahoria'],
    ['🥐', 'cruasán'],
    ['🧀', 'queso'],
    ['🥚', 'huevo'],
    ['🍔', 'hamburguesa'],
    ['🍟', 'patatas fritas'],
    ['🍕', 'pizza'],
    ['🌮', 'taco'],
    ['🥘', 'paella (sartén)'],
    ['🍝', 'espaguetis (pasta)'],
    ['🍣', 'sushi'],
    ['🍩', 'dónut'],
    ['🍪', 'galleta'],
    ['🎂', 'tarta de cumpleaños'],
    ['🍫', 'chocolate'],
    ['🍿', 'palomitas'],
    ['☕', 'café'],
    ['🍵', 'té'],
    ['🍺', 'cerveza'],
    ['🍷', 'vino'],
    ['🧉', 'mate']
  ],
  actividades: [
    ['⚽', 'balón de fútbol'],
    ['🏀', 'baloncesto'],
    ['🏈', 'fútbol americano'],
    ['⚾', 'béisbol'],
    ['🎾', 'tenis'],
    ['🏐', 'voleibol'],
    ['🏓', 'ping pong'],
    ['🥊', 'guante de boxeo'],
    ['⛳', 'golf'],
    ['🎿', 'esquí'],
    ['🏄', 'surf'],
    ['🚴', 'ciclismo (bici)'],
    ['🏆', 'trofeo (ganador)'],
    ['🥇', 'medalla de oro'],
    ['🎮', 'mando de videojuegos'],
    ['🕹️', 'joystick (arcade)'],
    ['🎲', 'dado'],
    ['♟️', 'peón de ajedrez'],
    ['🧩', 'pieza de puzle'],
    ['🎯', 'diana (objetivo)'],
    ['🎨', 'paleta de pintor (arte)'],
    ['🎬', 'claqueta de cine'],
    ['🎤', 'micrófono (karaoke)'],
    ['🎧', 'auriculares (música)'],
    ['🎸', 'guitarra'],
    ['🎹', 'piano (teclado musical)'],
    ['🥁', 'tambor'],
    ['🎉', 'confeti (fiesta)'],
    ['🎁', 'regalo'],
    ['🎈', 'globo']
  ],
  viajes: [
    ['🚗', 'coche'],
    ['🚕', 'taxi'],
    ['🚌', 'autobús'],
    ['🚓', 'coche de policía'],
    ['🚑', 'ambulancia'],
    ['🚒', 'camión de bomberos'],
    ['🏎️', 'coche de carreras'],
    ['🏍️', 'moto'],
    ['🚲', 'bicicleta'],
    ['🛴', 'patinete'],
    ['🚂', 'locomotora (tren)'],
    ['✈️', 'avión'],
    ['🚀', 'cohete'],
    ['🛸', 'platillo volante (ovni)'],
    ['🚁', 'helicóptero'],
    ['⛵', 'velero (barco)'],
    ['⚓', 'ancla'],
    ['🗺️', 'mapa'],
    ['🧭', 'brújula'],
    ['🏔️', 'montaña nevada'],
    ['🏖️', 'playa con sombrilla (vacaciones)'],
    ['🏝️', 'isla desierta'],
    ['🏕️', 'acampada (camping)'],
    ['🏠', 'casa'],
    ['🏰', 'castillo'],
    ['🗽', 'estatua de la libertad'],
    ['🌋', 'volcán'],
    ['🌍', 'globo terráqueo (mundo)'],
    ['🌃', 'noche estrellada (ciudad)']
  ],
  objetos: [
    ['⌚', 'reloj'],
    ['📱', 'teléfono móvil'],
    ['💻', 'portátil (ordenador)'],
    ['⌨️', 'teclado'],
    ['🖱️', 'ratón de ordenador'],
    ['💾', 'disquete (guardar)'],
    ['📷', 'cámara de fotos'],
    ['📺', 'televisión'],
    ['💡', 'bombilla (idea)'],
    ['🔦', 'linterna'],
    ['📚', 'libros'],
    ['✏️', 'lápiz'],
    ['📎', 'clip'],
    ['📌', 'chincheta'],
    ['✂️', 'tijeras'],
    ['🔑', 'llave'],
    ['🔒', 'candado cerrado'],
    ['🔨', 'martillo'],
    ['🛠️', 'herramientas'],
    ['⚙️', 'engranaje (ajustes)'],
    ['🧲', 'imán'],
    ['🧪', 'tubo de ensayo (ciencia)'],
    ['🔭', 'telescopio'],
    ['💊', 'pastilla'],
    ['🎒', 'mochila'],
    ['💰', 'bolsa de dinero'],
    ['💎', 'diamante (gema)'],
    ['☂️', 'paraguas'],
    ['📦', 'paquete (caja)'],
    ['✉️', 'sobre (carta, email)']
  ],
  simbolos: [
    ['❤️', 'corazón rojo'],
    ['🧡', 'corazón naranja'],
    ['💛', 'corazón amarillo'],
    ['💚', 'corazón verde'],
    ['💙', 'corazón azul'],
    ['💜', 'corazón morado'],
    ['🖤', 'corazón negro'],
    ['💔', 'corazón roto'],
    ['✨', 'destellos (brillos)'],
    ['⭐', 'estrella'],
    ['🔥', 'fuego'],
    ['💯', 'cien puntos'],
    ['✅', 'marca de verificación (hecho)'],
    ['❌', 'cruz (error)'],
    ['❓', 'signo de interrogación (pregunta)'],
    ['❗', 'signo de exclamación'],
    ['⚠️', 'advertencia (peligro)'],
    ['🚫', 'prohibido'],
    ['♻️', 'reciclaje'],
    ['⚡', 'rayo (alto voltaje)'],
    ['💤', 'zzz (dormir)'],
    ['💬', 'bocadillo de diálogo (mensaje)'],
    ['🆕', 'nuevo'],
    ['🔔', 'campana (notificación)'],
    ['🎵', 'nota musical'],
    ['➕', 'más (sumar)'],
    ['🏳️‍🌈', 'bandera arcoíris'],
    ['🇪🇸', 'bandera de España'],
    ['🇲🇽', 'bandera de México'],
    ['🇦🇷', 'bandera de Argentina']
  ]
}

// Aplanamos los datos: [{ emoji, name, category }, ...]
export const EMOJIS = Object.entries(DATA).flatMap(([category, list]) =>
  list.map(([emoji, name]) => ({ emoji, name, category }))
)
